### ISSUE TITLE
End to End 和 Encoder Decoder是啥区别

### ISSUE THREAD

**Issue by xjock** [ViTAE-Transformer/SAMRS#17]
如图所述，Encoder Decoder可以跑通，End to End不行

**Comment by DotWang** [comment]
@xjock Encoder Decoder是传统的编码器-解码器结构，像UNet，UperNet之类的，End to End是Mask2Former这种端到端的，跑不通是指？如果是报错，我没看见图，如果是效果不如Encoder-Decoder的，这个在文中讲了
“We notice SEP played a negative role in the end-to-end structure, it may be because the objects of SAMRS are too small, which is unfavorable for the region-based Mask2Former. In addition, the Mask2Former, which has obtained high accuracies on natural images, does not perform as well as UNet and UperNet on RSIs. These results indicate more refined parameter adjustments of Mask2Former are needed in later research.”
